server:
  port: 8080
  servlet:
    context-path: /

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      base-path: /admin

logging:
  config: file:src/main/resources/logback-dev.xml